#!/bin/bash
if [ "$1" != "-d" ];then
echo "usage: $0 -d dir"
exit 8
fi

if [ -d $2 ]
	then echo "$2目录已存在"
	exit 8	
fi
mkdir -p $2
cd $2

starttime=$(date +%s)


declare -A dbConfMap
confFile=/home/peter/dev_project/sh_lite/db.conf
# 设置IFS,将分隔符设置为换行符
OLDIFS=$IFS
IFS=$'\n'
# 读取文件中的内容到数组中
confArr=($(cat $confFile))

# 恢复之前的设置
IFS=$OLDIFS
for i in "${!confArr[@]}";
do
{
	val=${confArr[$i]}
	kvpairArr=(${val//=/ })
	dbConfMap["${kvpairArr[0]}"]="${kvpairArr[1]}"
}
done

#王燕中间数据库配置
miduser2=${dbConfMap["miduser"]}
midhost2=${dbConfMap["midhost"]}
midpwd2=${dbConfMap["midpwd"]}
middb2=${dbConfMap["middb"]}

#b2b业务库配置
b2bbizhost=${dbConfMap["b2bbizhost"]}
b2bbizuser=${dbConfMap["b2bbizuser"]}
b2bbizpwd=${dbConfMap["b2bbizpwd"]}
b2bbizdb=${dbConfMap["b2bbizdb"]}

#ERP集中库配置
erpcenterhost=${dbConfMap["erpcenterhost"]}
erpcenterport=${dbConfMap["erpcenterport"]}
erpcenteruser=${dbConfMap["erpcenteruser"]}
erpcenterpwd=${dbConfMap["erpcenterpwd"]}
erpcenterservice=${dbConfMap["erpcenterservice"]}

#validate库配置
validhost=${dbConfMap["validhost"]}
validuser=${dbConfMap["validuser"]}
validpwd=${dbConfMap["validpwd"]}
validdb=${dbConfMap["validdb"]}




tables=(tb_cen_account_o_storeinven tb_cen_storenotavailableqty tb_gos_stock_stockpreemption)
fields=("pk, fk, lineid, lastmodifytime, createtime, branchid, prodid, invbalqty, invbalamt, storeid, deleteflag, note, version" 
		"pk, createtime, lastmodifytime, version, branchid, storeid, prodid, notavailableqty, preassignedqty, runningno, note"
		 "pk, fk, createtime, lastmodifytime,version, lineid, branchid, deleteflag, note, preemptionpreemption, prodid, lotno, quantity, rowguid, billid, whseid, storeid, billguid, opid, custid, custno, custname")

		 erpFieldsSql=("pk||','|| fk||','|| lineid||','|| to_char(lastmodifytime,'yyyy-mm-dd hh24:mi:ss')||','|| to_char(createtime,'yyyy-mm-dd hh24:mi:ss')||','|| branchid||','|| prodid||','|| invbalqty||','|| invbalamt||','|| storeid||','|| deleteflag||','|| note||','|| version" "pk||','||to_char(createtime,'yyyy-mm-dd hh24:mi:ss')||','|| to_char(lastmodifytime,'yyyy-mm-dd hh24:mi:ss')||','|| version||','|| branchid||','|| storeid||','||prodid||','||notavailableqty||','|| preassignedqty||','||runningno||','|| note" "pk||','||fk||','|| to_char(createtime,'yyyy-mm-dd hh24:mi:ss')||','|| to_char(lastmodifytime,'yyyy-mm-dd hh24:mi:ss')||','||version||','|| lineid||','|| branchid||','|| deleteflag||','||note||','||to_char(preemptionpreemption,'yyyy-mm-dd hh24:mi:ss')||','||prodid||','||lotno||','|| quantity||','|| rowguid||','||billid||','||whseid||','|| storeid||','||billguid||','||opid||','||custid||','|| custno||','|| custname")
where="where branchid = 'FDW' "


for i in "${!tables[@]}";   
do
{
	tablename=${tables[$i]}
	field=${fields[$i]}

	mysqlSelectSql="select ${field} from ${tablename} ${where} ;"
	{
	mysql -h${midhost} -u${miduser} -p${midpwd} ${middb} -e"${mysqlSelectSql}"	> mid_${tablename}.mid
	} &
	field=${erpFieldsSql[$i]}
	oracleSelectSql="select ${field} from ${tablename} ${where} ;"
	{
	sqlplus ${erpcenteruser}/${erpcenterpwd}@${erpcenterhost}:${erpcenterport}/${erpcenterservice} <<!
		set linesize 2000
		set colsep ''
		set heading off
		set feedback off
		set pagesize 0
		set verify off
		set newp none
		set echo off
		spool $(pwd)/${tablename}
		${oracleSelectSql}
		spool off
!
	} &
}
done
wait
echo "数据导出完毕,开始整理.."

endtime=$(date +%s)
echo "export data waste time:$(expr ${endtime} - ${starttime})"

for i in "${!tables[@]}";   
do
{
	tablename=${tables[$i]}
	sed -i "1d" mid_${tablename}.mid && awk -F '\t' '{a="";for(i=1;i<=NF;i++){if(a==""){a=$i;}else{a=a","$i;} }print a;}' mid_${tablename}.mid | sed "s/NULL//g" > mid_${tablename} && rm mid_${tablename}.mid &
	mv ${tablename}.lst erp_${tablename} && sed -i -e"1d" -e"\$d" erp_${tablename} &
}
done

wait
echo "数据整理完毕!"

for i in "${!tables[@]}";
do
	tablename=${tables[$i]}
	echo "$(wc -l *${tablename} | sed '$d')"
done
