#!/bin/bash
if [ "$1" != "-d" ];then
echo "usage: $0 -d dir"
exit 8
fi

if [ -d $2 ]
	then echo "$2目录已存在"
	exit 8	
fi
mkdir -p $2
cd $2

starttime=$(date +%s)


#中间数据库配置
miduser=xxx
midhost=xxx
midpwd=xxx
middb=xxx

#b2b业务库配置
b2bbizhost=xxx
b2bbizuser=xxx
b2bbizpwd=xxx
b2bbizpwd=xxx

#ERP集中库配置
erpcenterhost=xxx
erpcenterport=xxx
erpcenteruser=xxx
erpcenterpwd=xxx
erpcenterservice=xxx




tables=(tb_cen_account_o_storeinven tb_cen_storenotavailableqty tb_gos_stock_stockpreemption)
fields=("pk, fk, lineid, lastmodifytime, createtime, branchid, prodid, invbalqty, invbalamt, storeid, deleteflag, note, version" 
		"pk, createtime, lastmodifytime, version, branchid, storeid, prodid, notavailableqty, preassignedqty, runningno, note"
		 "pk, fk, createtime, lastmodifytime,version, lineid, branchid, deleteflag, note, preemptionpreemption, prodid, lotno, quantity, rowguid, billid, whseid, storeid, billguid, opid, custid, custno, custname")

		 erpFieldsSql=("pk||','|| fk||','|| lineid||','|| to_char(lastmodifytime,'yyyy-mm-dd hh24:mi:ss')||','|| to_char(createtime,'yyyy-mm-dd hh24:mi:ss')||','|| branchid||','|| prodid||','|| invbalqty||','|| invbalamt||','|| storeid||','|| deleteflag||','|| note||','|| version" "pk||','||to_char(createtime,'yyyy-mm-dd hh24:mi:ss')||','|| to_char(lastmodifytime,'yyyy-mm-dd hh24:mi:ss')||','|| version||','|| branchid||','|| storeid||','||prodid||','||notavailableqty||','|| preassignedqty||','||runningno||','|| note" "pk||','||fk||','|| to_char(createtime,'yyyy-mm-dd hh24:mi:ss')||','|| to_char(lastmodifytime,'yyyy-mm-dd hh24:mi:ss')||','||version||','|| lineid||','|| branchid||','|| deleteflag||','||note||','||to_char(preemptionpreemption,'yyyy-mm-dd hh24:mi:ss')||','||prodid||','||lotno||','|| quantity||','|| rowguid||','||billid||','||whseid||','|| storeid||','||billguid||','||opid||','||custid||','|| custno||','|| custname")
where="where branchid = 'FDW' "


for i in "${!tables[@]}";   
do
{
	tablename=${tables[$i]}
	field=${fields[$i]}

	mysqlSelectSql="select ${field} from ${tablename} ${where} ;"
	{
	mysql -h${midhost} -u${miduser} -p${midpwd} ${middb} -e"${mysqlSelectSql}"	> mid_${tablename}.mid
	} &
	field=${erpFieldsSql[$i]}
	oracleSelectSql="select ${field} from ${tablename} ${where} ;"
	{
	sqlplus ${erpcenteruser}/${erpcenterpwd}@${erpcenterhost}:${erpcenterport}/${erpcenterservice} <<!
		set linesize 2000
		set colsep ''
		set heading off
		set feedback off
		set pagesize 0
		set verify off
		set newp none
		set echo off
		spool $(pwd)/${tablename}
		${oracleSelectSql}
		spool off
!
	} &
}
done
wait
echo "数据导出完毕,开始整理.."

endtime=$(date +%s)
echo "export data waste time:$(expr ${endtime} - ${starttime})"

for i in "${!tables[@]}";   
do
{
	tablename=${tables[$i]}
	sed -i "1d" mid_${tablename}.mid && awk -F '\t' '{a="";for(i=1;i<=NF;i++){if(a==""){a=$i;}else{a=a","$i;} }print a;}' mid_${tablename}.mid | sed "s/NULL//g" > mid_${tablename} && rm mid_${tablename}.mid &
	mv ${tablename}.lst erp_${tablename} && sed -i -e"1d" -e"\$d" erp_${tablename} &
}
done

wait
echo "数据整理完毕!"

for i in "${!tables[@]}";
do
	tablename=${tables[$i]}
	echo "$(wc -l *${tablename} | sed '$d')"
done
